# Generated by Django 4.0.2 on 2022-02-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0007_libro_estado_alter_autor_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='estado',
        ),
        migrations.AddField(
            model_name='autor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
